global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 30s
    static_configs:
      - targets: 
          - 'docker1:9100'
          - 'docker2:9100'
          - 'rancher:9100'
          - 'gluster1:9100'
          - 'gluster2:9100'
          - 'gluster3:9100'
          - 'cassandra1:9100'
          - 'cassandra2:9100'
          - 'cassandra3:9100'
          - 'kafka1:9100'
          - 'kafka2:9100'
          - 'kafka3:9100'

  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: 
          - 'docker1:8080'
          - 'docker2:8080'

  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'cassandra'
    scrape_interval: 30s
    static_configs:
      - targets:
          - 'cassandra1:9404'
          - 'cassandra2:9404'
          - 'cassandra3:9404'

  - job_name: 'kafka'
    scrape_interval: 30s
    static_configs:
      - targets:
          - 'kafka1:9404'
          - 'kafka2:9404'
          - 'kafka3:9404'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
