---
- 
  hosts: gluster-client

  tasks:
  - name: Install packages
    apt: 
      pkg: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'acl']
      state: present

  - name: apt repository
    apt_repository: repo="ppa:gluster/glusterfs-{{ gluster_version }}" state=present
    notify: update apt cache

  - name: Install glusterfs-client
    apt: pkg="glusterfs-client" state=present

  - name: directory /persistence
    file: path=/persistence state=directory mode=0755 owner=root group=root

  - name: mount glusterfs
    mount: path=/persistence src=gluster1:vol0 fstype=glusterfs state=mounted

  handlers:
  - name: update apt cache
    apt: update_cache=yes

